import 'dart:ui';
import 'dart:ui' show ImageFilter;

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:latihan1/cubit/cubit.dart';
import 'package:share/share.dart';
import 'package:supercharged/supercharged.dart';
import 'package:latihan1/shared/shared.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter/cupertino.dart';
import 'package:latihan1/widgets/widgets.dart';
import 'package:latihan1/models/models.dart';
import 'package:flutter_custom_clippers/flutter_custom_clippers.dart';
import 'package:get/get.dart';
import 'package:form_field_validator/form_field_validator.dart';
import 'package:snapping_sheet/snapping_sheet.dart';

part 'main_page.dart';
part 'general_page.dart';
part 'sign_in_page.dart';
part 'home_page.dart';
part 'perusahaan_detail_page.dart';
part 'illustration_page.dart';
part 'bookmark_page.dart';
part 'profile_page.dart';
part "general_profile_page.dart";
part "general_pages_awal.dart";
part "sign_up_page.dart";
part "complete_signup.dart";
part "ganti_password.dart";
part 'sliver_page.dart';
part 'cari.dart';
part "kebijakan.dart";
part "search.dart";
